#!/bin/bash
#
#SBATCH --job-name=physlr1
#SBATCH --exclusive
#SBATCH --output=%x_%j.log
#SBATCH --workdir=/projects/btl/gdilek/physlr/src/log

set -euo pipefail

cd /projects/btl/gdilek/physlr/src

/usr/bin/time -pv -o cppfb.f1chr4.time ./physlr-filter-barcodes ../data/f1chr4.indexlr.physlr.tsv -n2 -N20 >cppfb.f1chr4 
/usr/bin/time -pv -o pyfm.f1chr4.time env PYTHONPATH=.. /projects/btl/aafshinfard/virtuEnv/pypy3/bin/pypy3 ../bin/physlr filter-minimizers -V2 -C10 cppfb.f1chr4 > pyfm.f1chr4

touch ${SLURM_JOB_NAME}.done
